stages:
  data_cleaning:
    cmd: python data_cleaning.py
    deps:
      - music_info.csv
      - data_cleaning.py
    outs:
      - cleaned_data.csv

  transform_data:
    cmd: python content_based_filtering.py
    deps: 
      - cleaned_data.csv
      - content_based_filtering.py
      - data_cleaning.py
    outs:
      - transformed_data.npz
      - transformer.joblib
